spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/capstone
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
#security:
#  jwt:
#    secret: "super-duper-mega-ultra-perfect-secret"
#    expiresAfterMin: 30

